# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080